### ISSUE TITLE
Closing threads

### ISSUE THREAD

**Issue by camjac251** [mtverlee/lars#18] opened 2019-04-13 11:05 UTC
I noticed that with a lot of channels, `main.py` seems to open in quite a few threads and only expands as each check happens. I currently have 70 threads of the main.py process running on just one instance with less than 15 channels monitored. It just increased to 75, I believe that after 30 minutes or so, it reached over 500. Is this intended? Or possibly that dead/inactive threads aren't killed before the new one is started?

**Comment by mtverlee** [comment] 2019-04-13 18:39
Threads are supposed to be closed by calling ```sys.exit()``` on them but I'll do some testing and see if they're not closing. What you're describing is definitely not intended behavior.

**Comment by camjac251** [comment] 2019-04-13 18:40
After a few hours of recording, it raised up to 500 threads.

**Comment by mtverlee** [comment] 2019-04-13 18:40
Yeah, there's definitely an issue then. I'll check it out and release a patch. :)

**Comment by mtverlee** [comment] 2019-04-14 07:10
This should be fixed as of [this](https://github.com/mtverlee/lars/commit/a8973075552fbdec6434ba4c88c0dfeeb5268380) commit. Let me know if you still have issues. Closed for now.

**Comment by camjac251** [comment] 2019-04-14 20:37
I did see a difference in the first 30 minutes of running it but after a couple of hours, my threads were at 2000.

**Comment by camjac251** [comment] 2019-04-15 12:05
It might not be working on Gentoo. I'm using virtualenv with Python 3.6 and it increases threads still. On Ubuntu it seemed to hold well after many hours but doesn't do the same in Gentoo

**Comment by camjac251** [comment] 2019-04-15 15:04
My virtual memory also goes up as well to 40+GB

**Comment by mtverlee** [comment] 2019-04-24 14:27
This issue should be fixed as of version 2.0 ([info](https://github.com/mtverlee/lars/commit/e6f3d1fa087b96ca1d7371125f42c38e7b39005c)). I've reworked the function spawning threads to use ```run()``` instead of ```start()```. This should cut down on the number of threads as threads should automatically terminate upon finishing their tasks. This breaks backwards compatibility and you will need to reinstall.

Apologies for taking so long. :)

**Closed by mtverlee** 2019-04-24 14:27 UTC
Labels: bug, currently investigating, help wanted
